### ISSUE TITLE
Buffers do not get restored when nerd tree is open when saving the session, and the current working directory is `~`

### ISSUE THREAD

**Issue by dylan-chong** [zefei/vim-wintabs#38] opened 2018-06-17 04:16 UTC
I don't have time to create a minimal vimrc file at the moment, I will try to get around to that sometime in the future (no guarantees when). But these are the replication steps:

1. Open Vim in your home directory
1. Open two files (i.e. buffers)
1. Open nerd tree
1. Save the session with vim-session
1. Close Vim
1. Reopen Vim. Only one of the two files is restored

**Comment by zefei** [comment] 2018-06-17 07:30
I can repro, will try to fix. No need for minimal vimrc.

**Comment by zefei** [comment] 2018-06-17 08:06
This looks like a special interaction between vim-session and Nerdtree. During the session load of Nerdtree, vim-session does some extra steps to restore Nerdtree, which in turn destroys the wintabs session. This wouldn't happen if you use `:mksession` and `:so`. So I'm afraid I can't fix this issue completely.

One way to mitigate the issue is that: when this happens, call `:WintabsAllBuffers`. This should be able to restore your buffers from last session.

**Comment by zefei** [comment] 2018-07-20 06:55
I'm closing this since it cannot be fixed since vim-session does a lot of extra stuff with nerdtree and disrupts normal wintabs buffer restore.

**Closed by zefei** 2018-07-20 06:55 UTC
