### ISSUE TITLE
Cannot WintabsClose the final modified buffer in a window.

### ISSUE THREAD

**Issue by jordwalke** [zefei/vim-wintabs#24] opened 2018-02-04 06:54 UTC
If you open Vim, and modify the default non-named buffer. It will show up as a wintab, but then if you try to WintabsClose it, you will get an error message:

<img width="686" alt="screen shot 2018-02-03 at 10 50 41 pm" src="https://user-images.githubusercontent.com/977348/35775021-26ee677e-0935-11e8-820b-68b45f8ed0bd.png">

```
set hidden
let g:tabSystem = 'wintabs'
let g:wintabs_autoclose=1
let g:wintabs_autoclose_vim=1
let g:wintabs_switchbuf='useopen,usetab'
let g:wintabs_ui_modified*
let g:wintabs_ui_active_higroup = 'TabLineSel'

```

Note that `let g:wintabs_autoclose=2` does work, but `let g:wintabs_autoclose=1` does not.

**Comment by zefei** [comment] 2018-02-05 07:02
Thanks for flagging this! Will fix it soonish.

**Comment by jordwalke** [comment] 2018-02-09 21:14
Related, you cannot even close any non-named buffer without raising this error (try `:enew`). One helpful datapoint: If before deleting the non-named buffer, you set `:setlocal bufhidden=hide` then the error doesn't happen. I think it's because with `bufhidden=delete` (or even the default value of empty string) the buffer is deleted twice - once by default and once by wintabs.

**Comment by jordwalke** [comment] 2018-02-09 21:23
And with the following config:
```
let g:wintabs_display='statusline'
set hidden
let g:wintabs_autoclose=2
let g:wintabs_autoclose_vim=1
let g:wintabs_autoclose_vimtab=1
let g:wintabs_switchbuf='useopen,usetab'
let g:wintabs_ui_active_higroup = 'TabLineSel'
```

As mentioned in the initial description closing the first/only non-named modified buffer works.

But then with that new config, closing the first/only  *named* buffer does not work if you have modifications.

**Comment by zefei** [comment] 2018-02-19 11:15
This should be fixed now. Thank you for the analysis @jordwalke, it helped me resolve another issue. Some of the edge cases we see here are indeed caused by wintab's reliance on the interaction between "confirm" and "hidden".

Due to the recent vim changes on "silent!"+"confirm", I'm not very sure if I'm fixing the right thing (I removed some "silent!" to bubble up exceptions). Please test out the new version and let me know if things still behave correctly and consistently.

**Closed** 2018-05-20 06:45 UTC
